from __future__ import annotations

from datetime import datetime
from typing import Iterable, Protocol

from quant_bot.domain.balance import Balance
from quant_bot.domain.fill import Fill
from quant_bot.domain.instrument import Instrument
from quant_bot.domain.market_data import MarketBar
from quant_bot.domain.order import Order
from quant_bot.domain.position import Position


class ExchangeAdapter(Protocol):
    """Capability boundary; implementations are intentionally absent here."""

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def health_check(self) -> bool: ...
    def load_instruments(self) -> Iterable[Instrument]: ...
    def stream_market_data(self, symbol: str) -> Iterable[MarketBar]: ...
    def fetch_balances(self) -> Iterable[Balance]: ...
    def fetch_positions(self) -> Iterable[Position]: ...
    def fetch_open_orders(self) -> Iterable[Order]: ...
    def fetch_recent_fills(self) -> Iterable[Fill]: ...
    def place_order(self, order: Order) -> object: ...
    def amend_order(self, client_order_id: str, changes: dict[str, object]) -> object: ...
    def cancel_order(self, client_order_id: str) -> object: ...
    def cancel_all(self) -> object: ...
    def reconcile_state(self) -> object: ...
    def get_server_time(self) -> datetime: ...
    def get_rate_limit_state(self) -> object: ...
